imds = imageDatastore('arousal', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
[imdsTrain,imdsValidation] = splitEachLabel(imds,0.8,'randomize');
augimdsTrain = augmentedImageDatastore([64 64],imdsTrain);
augimdsValidation = augmentedImageDatastore([64 64],imdsValidation);
options = trainingOptions('sgdm', ...
  'MiniBatchSize',128, ...
  'MaxEpochs',20, ...
  'InitialLearnRate',1e-2, ...
  'Shuffle','every-epoch', ...
  'ValidationData',augimdsValidation, ...
  'ValidationFrequency',10, ...
  'Verbose',false, ...
  'Plots','training-progress');
net = trainNetwork(augimdsTrain,lgraph_2,options);